Homebrew/ruby-macho

lib/macho/load_commands.rb
@woodruffw Do you prefer to have PRs for fixes like this one or are you comfortable with me pushing something like this directly to `master`?
=> EncryptionInfoCommand64: add missing argument

lib/macho/exceptions.rb, lib/macho/fat_file.rb, lib/macho/headers.rb, lib/macho/load_commands.rb, lib/macho/macho_file.rb, lib/macho/sections.rb, test/test_fat.rb, test/test_macho.rb
Additionally, adds new CPU types and subtypes, as well as two
additional load commands and freezes declared data structures.
@UniqMartin These are mostly your changes, plus some of the constants I added in #24.
=> Improve cputype/cpusubtype handing.

lib/macho/fat_file.rb, lib/macho/headers.rb, lib/macho/load_commands.rb, lib/macho/macho_file.rb, lib/macho/sections.rb, lib/macho/structure.rb, lib/macho/utils.rb, test/helpers.rb, test/src/Makefile, test/test_fat.rb, test/test_macho.rb
=> PPC (general big-endian) support

lib/macho/load_commands.rb
Adds `SymsegCommand` (`LC_SYMSEG`), `FvmlimCommand` (`LC_LOADFVMLIB`, `LC_IDFVMLIB`), `IdentCommand` (`LC_IDENT`), and `FvmfileCommand` (`LC_FCMFILE`).
`libmacho` doesn't seem to expose a pubic definition for the structure associated with `LC_PREPAGE`, so that one will have to remain unimplemented for now.
=> Add obsolete and internal load commands.

lib/macho/macho_file.rb
Some more triage on `set_lc_str_in_cmd` while I work on an ultimate replacement.
Having a discrete `MachOFIle#low_fileoff` method will probably come in handy, since `low_fileoff` appears in a few places in `libmacho` and will certainly come in handy for the upcoming `MachOFile#add_command` (or whatever we settle on).
Replacing `String#size` with `String#bytesize` doesn't cause any of our current tests to break, and is probably the best temporary fix for any internationalization issues we come across.
cc @UniqMartin
=> macho_file: Add low_fileoff method, use String#bytesize for LC strings.

lib/macho/macho_file.rb
=> macho_file: General refactoring.

lib/macho/fat_file.rb, lib/macho/macho_file.rb, lib/macho/tools.rb, test/test_fat.rb, test/test_macho.rb, test/test_tools.rb
~~- [ ] Rpath addition~~
~~Addition support is blocking on #38. Once we merge that in, I can fill the necessary bits in here :smile:~~
cc @UniqMartin
=> Rpath deletion.

lib/macho/exceptions.rb, lib/macho/fat_file.rb, lib/macho/macho_file.rb, lib/macho/tools.rb, test/test_fat.rb, test/test_macho.rb, test/test_tools.rb
Broken off from #40. ~~WIP until #38 is merged.~~
cc @UniqMartin
=> Rpath addition.

lib/macho/load_commands.rb
Not much to say about this one. Not sure why it wasn't a subclass already...
=> Make RoutinesCommand64 a subclass of RoutinesCommand.

.travis.yml, Gemfile, Rakefile, bin/change_id.rb, bin/change_int.rb, bin/fat_test.rb, bin/info.rb, ruby-macho.gemspec, run-tests, test/bench.rb, test/helpers.rb, test/test_fat.rb, test/test_macho.rb, test/test_open.rb, test/test_serialize_load_commands.rb
This PR will also be used to fix rubocop's complaints outside of *lib/*.
=> travis: Add rubocop to CI.

lib/macho/fat_file.rb, lib/macho/load_commands.rb, lib/macho/macho_file.rb, lib/macho/sections.rb, lib/macho/utils.rb, test/test_macho.rb
=> Proper fat Mach-O creation

Gemfile.lock, lib/macho/fat_file.rb, lib/macho/headers.rb, lib/macho/load_commands.rb, lib/macho/macho_file.rb, lib/macho/sections.rb
=> Rubocop 0.59.0

lib/macho/exceptions.rb, lib/macho/load_commands.rb
Will rebase #175 after this goes through.
=> macho: Use <annotated_tokens> for formatting

.github/workflows/release.yml
Simplifies the release workflow, slightly.
=> workflows/release: Add a release workflow

.github/workflows/tests.yml, .rubocop.yml, ruby-macho.gemspec
The current version is 3.0, and 2.5 is EOL.
=> Update Ruby versions being tested

lib/macho/macho_file.rb, lib/macho/tools.rb, test/test_macho.rb
=> Add `:uniq` kwarg to `#delete_rpath` and `#change_rpath`

lib/macho/fat_file.rb
For consistency with the changes in #366.
=> fat_file: update YARD docs

.github/workflows/tests.yml, lib/macho/load_commands.rb
I introduced a small bug with my suggestion on #425. This fixes it.
=> macho/load_commands: fix FilesetEntryCommand::SIZEOF

lib/macho.rb
=> macho: 3.0.0

.github/workflows/tests.yml
=> workflows/tests: add ruby 3.3 to matrix

docs/machostructure-dsl.md, lib/macho/structure.rb
Cleaning up minor typos across our repos.
=> various: fix miscellaneous typos

lib/macho.rb
=> macho: 4.0.1

.github/workflows/tests.yml
In principle, this will unbreak our CI coverage.
=> tests: set CODECOV_TOKEN

lib/macho/headers.rb
See https://github.com/apple-oss-distributions/cctools/blob/7a5450708479bbff61527d5e0c32a3f7b7e4c1d0/include/mach-o/loader.h.
=> headers: add some new constants

.github/workflows/tests.yml
This is the org default but make it explicit.
=> workflows/tests: set permissions
