Homebrew/ruby-macho

lib/macho/load_commands.rb
lib/macho/macho_file.rb

Linked dylibs are not limited to the `LC_LOAD_DYLIB` load command. For completeness and consistency with `otool -L`, consider all relevant load commands (all with a `DylibCommand` structure, except `LC_ID_DYLIB`).
Also adjust `change_install_name` to work the same on the modification side and for consistency with `install_name_tool`.
One way to see a real-world issue due to this is to use `brew linkage qt5` (from [`homebrew/dev-tools`](https://github.com/Homebrew/homebrew-dev-tools)) on a normal `qt5` build. The output will be different depending on whether or not `HOMEBREW_RUBY_MACHO` is set because Qt uses weak linkage. (Discovered while testing Homebrew/homebrew#45001.)
(Not sure what your goals for testing are, so here's just the fix without any tests for now.)

consider all relevant commands in 'linked_dylibs'

---

lib/macho/fat_file.rb

If there are no duplicates, `uniq!` returns nil instead of the array it operated on. Also use `flat_map` instead of `map` followed by `flatten` for performance reasons.
Possible alternatives:
- Reduce method to a single line: `machos.flat_map(&:linked_dylibs).uniq`.
- Retain the `dylibs.uniq!`, but add a line with just `dylibs` to return (the possibly unmodified) array.
One way to see a real-world failure due to this is to use `brew linkage gcc` (from [`homebrew/dev-tools`](https://github.com/Homebrew/homebrew-dev-tools)) on a `gcc` built with the `--without-multilib` option. The `lib/gcc/5/libgcc_s.1.dylib` will be a fat file with a single architecture and thus no duplicate dylib dependencies. (Originally discovered by testing against your PR Homebrew/homebrew#45001 with …

fix 'linked_dylibs' for fat files with single arch

---

lib/macho/headers.rb

`CPU_TYPE_X86` and `CPU_TYPE_I386` have the same numeric value, making the `CPU_TYPE_X86 => "CPU_TYPE_X86"` entry in `CPU_TYPES` useless as it is immediately overwritten in the following line.
Use `CPU_TYPE_I386` everywhere as that's the constant used in newer versions of the [`mach/machine.h` header](http://www.opensource.apple.com/source/cctools/cctools-877.5/include/mach/machine.h) (linked file is from `cctools-877.5`).

eliminate CPU_TYPE_X86 in favor of CPU_TYPE_I386

---

lib/macho/fat_file.rb
lib/macho/macho_file.rb

Here's an example of a non-fat binary that links multiple times to the same dylib:
- `$(brew --cellar)/go/1.5.3/libexec/bin/godoc`
Here are some examples of fat binaries provided by the system (on OS X 10.11.3) that link to different subsets of libraries depending on architecture (differences can be inspected with `otool -arch <arch> -L <file>`, where `<arch>` is one of `i386`, `x86_64`):
- `/System/Library/CoreServices/Photo Library Migration Utility.app/Contents/Frameworks/iLifeSlideshow.framework/Versions/A/iLifeSlideshow`
- `/System/Library/PrivateFrameworks/iTunesAccess.framework/Versions/A/iTunesAccess`
- `/System/Library/Video/Plug-Ins/AppleProResCodec.bundle/Contents/MacOS/AppleProResCodec`

Always return unique list of dylibs and clarify comments

---

lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/macho_file.rb

The commits go into a bit more detail, but the idea is to rely more on `MachOStructure.new_from_bin` for handling the structs instead of replicating that logic (and basically ignoring `FORMAT`), thus making it more likely to create inconsistencies.
*For full disclosure where I hope this leads to:* This is one (of possibly several) preparatory PRs to pave the way for full endian awareness in the code. In a local branch I have already hacked together everything so that the code is able to correctly read 32/64-bit x86/PPC/ARM binaries. (I cross-checked with `otool` to a reasonable extent and let it crunch through most of my system disk.)

FatFile/MachOFile: avoid some code duplication

---

Gemfile
Rakefile
test/bench.rb
test/helpers.rb

Add test_bench.rb, which will contain benchmarking tests
for both ruby-macho and otool/install_name_tool.
Add benchmark/ips as a dependency to conduct the forthcoming
benchmarks.
Add Helpers.installed? to selectively run benchmark tests
if external utilities are not available.
cc @UniqMartin, @xu-cheng 
ref #7

Testing: Add skeleton for new benchmarking tests.

---

.travis.yml
Rakefile
lib/macho/fat_file.rb
test/bench.rb
test/helpers.rb
test/test_fat.rb
test/test_macho.rb
test/test_open.rb
test/test_tools.rb

1.8.7 Compatibility

---

bin/fat_test.rb
bin/info.rb
lib/macho.rb
lib/macho/exceptions.rb
lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/open.rb
lib/macho/sections.rb
lib/macho/structure.rb
lib/macho/tools.rb
lib/macho/utils.rb
test/bench.rb
test/helpers.rb
test/test_fat.rb
test/test_macho.rb
test/test_open.rb
test/test_tools.rb

Everybody else in the Ruby world uses two-space, so we
should too.

Maintenance: Replace tab indentation with two-space.

---

lib/macho/exceptions.rb
lib/macho/fat_file.rb
lib/macho/macho_file.rb
test/helpers.rb
test/test_fat.rb
test/test_macho.rb

There are two edge cases early-on in the parsing process:
files too small to have a valid magic number and files
with valid magic but invalid contents (most notably, Java
classfiles).
The NotAMachOError class covers both of these cases, and is raised
in FatFile#get_fat_header and MachOFile#get_and_check_magic.
cc @UniqMartin

Error Handling: Add NotAMachOError for edge cases.

---

lib/macho/macho_file.rb

With Ruby from `homebrew/versions/ruby187` (1.8.7-p374) on OS X 10.11.3 `2**64` unfortunately yields `0` instead of the correct value. Setting this to the size of the raw data works around that issue and should work equally well, as the size of the entire Mach-O binary should be a sane upper limit for this.
In practice, the size of a Mach-O binary is already limited to 32 bits because the elements of `FatArch` and many offsets used in load commands are only 32 bits wide.
Without this fix, running the test suite failed for me for all tests that modify a Mach-O binary. This fix, even if Ruby is at fault, is important because we use the same version of Ruby in our 10.9 CI.
(I also snuck in a stylistic change in the second commit.)

MachOFile#set_lc_str_in_cmd: Fix Ruby 1.8.7 bug 

---

.gitignore
Gemfile.lock
run-tests

While testing locally with a bunch of different Rubies I found it quite cumbersome to set everything up. The result is `run-tests` which for me simplifies things down to a `with-ruby 1.8 ./run-tests`. As a kind of precondition I felt compelled to re-organize `.gitignore` and sort out the `Gemfile.lock` situation. (I hope I haven't missed anything by moving around and anchoring the ignore rules.)
@woodruffw Not sure what your local setup looks like, so I'm not sure if I'm only doing myself a favor and cluttering up your repository root or if my script is useful enough to occupy that spot.

Testing: Simplify running the test suite

---

lib/macho/fat_file.rb
lib/macho/macho_file.rb
lib/macho/open.rb
test/test_open.rb

Instead of attempting to open a file with `MachOFile.new `and catching
a `FatBinaryError` to attempt `FatFile.new`, read a few bytes and do some
magic/sanity tests. Once sanity is established, instantiate either a
`MachOFile` or a `FatFile`.
Tasks:
Reference: #7

Optimization: Replace control-flow-by-exception with magic testing and incremental reads.

---

lib/macho.rb
lib/macho/headers.rb

@UniqMartin How much completeness do you think we should aim for re: CPU types and subtypes?
I'm thinking about filling out every group that appears in [arch.c](https://opensource.apple.com/source/cctools/cctools-877.8/libstuff/arch.c), as these are the ones that certainly had binaries built (or at least targets available) at some point. We probably won't ever run into an HPPA Mach-O, but it can't hurt to parse one correctly at no additional cost.

headers: Add additional ARM subtypes, correct errors.

---

README.md
lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/macho_file.rb
test/test_fat.rb
test/test_macho.rb

Low priority, just a nice-to-have in a future release.
cc @UniqMartin 
ref https://github.com/Homebrew/brew/pull/378#issuecomment-226939348

Use symbols to represent filetypes instead of strings.

---

lib/macho.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/structure.rb
lib/macho/view.rb

This was an oversight on my part, but we're going to need `endianness` in a good number
of load commands in order to extract things like symbol/hint tables in an encapsulated fashion (i.e., not returning flow back to the main `MachOFile`/`FatFile` object every time we need data relevant to a LC).
Once it's in, I can open PRs for my branches that implement the tables/internal structures relevant to various LCs.
cc @UniqMartin

Make endianness an attribute of all LCs.

---

lib/macho/fat_file.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/open.rb
lib/macho/structure.rb
lib/macho/utils.rb

This one is *probably* safe to merge, but I'd like some tests before I do so.
Do you have any ideas on getting `clang`/`ld` to emit a two-level namespace hints lookup table?
cc @UniqMartin

Add direct two-level hints table access.

---

lib/macho/load_commands.rb

- Drop constructor argument `raw_data` as it is redundant and the data can be obtained from the load command via `lc.view.raw_data` (and adapt related load commands accordingly).
- Use intermediate variables to shorten overly long line.
- Avoid storing constructor arguments in instance variables if they are not going to be referenced later (`@raw_data` and `@lc`).
- Improve names of instance variables.
@woodruffw Sorry that this is somewhat interfering with #33 where you add new load commands that also use `LCStr` (but obviously still using the three-argument constructor).

LCStr: Refactor and simplify

---

lib/macho/fat_file.rb
lib/macho/macho_file.rb
test/test_fat.rb
test/test_macho.rb

At the moment, `rpath` modification fails on x86_64 binaries.
I'll be looking into why that is, and this PR will serve as the location for that research (and eventual fix).

(Correct) RPath support.

---

lib/macho/tools.rb
test/test_tools.rb

`Tools.add_rpath` and `Tools.delete_rpath` remain unimplemented, for the time being. I'll be implementing those in another PR.
The first shouldn't be too hard once creation/serialization of LCs is completed, and the second is just a matter of finding the right LC and removing it entirely (and updating `sizeofcmds`).

Add rpath changing to tools, tests.

---

lib/macho/exceptions.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/utils.rb
test/helpers.rb
test/test_create_load_commands.rb
test/test_serialize_load_commands.rb

Downsides to this approach:
* Argument order is currently unchecked, which means that users will almost certainly run into confusing bugs if they provide arguments in the order not used by structures in `libmacho` (and `ruby-macho`).
cc @UniqMartin

Add LoadCommand.create for creating independent load commands.

---

lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/sections.rb
lib/macho/structure.rb
lib/macho/utils.rb

* Properly mark constants as private.
* Fill in some missing method descriptions and correct
formatting errors.
* Prefer "@api private" to "@private" from here on out.
This is low priority, since it doesn't actually change anything in code. On the other hand, it finally gets us to 100% yardoc coverage :tada: 
cc @UniqMartin

Documentation shoring

---

lib/macho/exceptions.rb
lib/macho/macho_file.rb
test/test_fat.rb
test/test_macho.rb
test/test_tools.rb

Additionally adds `MachOFile#populate_fields`, `MachOFile#replace_command`, `MachOFile#insert_command`, and `MachOFile#delete_command`, and generalizes the case where we delete multiple commands in batch and defer field synchronization until the end.
In the spirit of #41, do we want to prevent `MachOFile#change_install_name` from producing duplicate dylibs? My suspicion is that we do, again against the behavior of `install_name_tool`.
cc @UniqMartin

Remove MachOFile#set_lc_str_in_cmd in favor of creation/serialization

---

lib/macho/macho_file.rb
test/test_macho.rb

Fixes a bug where all changed install names were turned into
LC_LOAD_DYLIB commands.
ref #51 
cc @UniqMartin

macho_file: Preserve a dylib's type when changing it.

---

lib/macho/exceptions.rb
lib/macho/load_commands.rb

Corrects behavior when the (normally null) padding of a load command
contains garbage data instead.
ref #52 
cc @UniqMartin

load_commands: Grab only the first null terminated string.

---

lib/macho/macho_file.rb
test/test_macho.rb

Prevents `MachOFile#change_rpath` from creating duplicates, and fixes a variable in `MachOFile#delete_rpath`.
ref #41
cc @UniqMartin

Rpath duplication prevention/bugfix.

---

lib/macho/exceptions.rb
lib/macho/fat_file.rb
lib/macho/macho_file.rb
lib/macho/tools.rb

Resolves the problem of valid discrepancies between individual Mach-Os in a fat
file causing exceptions during modifications.
ref #50 
cc @UniqMartin

Allow suppression of exceptions with strict: false

---

lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/sections.rb
test/test_macho.rb

New code should always prefer `SegmentCommand#sections` over `MachOFile#sections`, as this better expresses the relationship between segments and their sections (and the parent Mach-O).
I'm leaving `MachOFile#sections` in for the time being (with a `@deprecated` warning), although all internal references to it have been removed. It might make sense to remove it before 1.0, though.
cc @UniqMartin

Deprecate MachOFile#sections in favor of SegmentCommand#sections.

---

.rubocop.yml
lib/macho/exceptions.rb
lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/open.rb
lib/macho/sections.rb
lib/macho/structure.rb
lib/macho/utils.rb

Another low-priority PR, just cleans up the code a bit and adds a `.rubocop.yml` for future style enforcement.
`rubocop` complains about roughly 100 other things in the `lib/` tree, although most of them are even less significant (methods over 10 lines, for example).
All of the unresolved violations are here: [ruby-macho-rubocop.txt](https://github.com/Homebrew/ruby-macho/files/392754/ruby-macho-rubocop.txt)
cc @UniqMartin

General refactoring.

---

test/test_serialize_load_commands.rb

This makes the test output a little less pretty, but more accurately reflects the fact that we're skipping tests of unimplemented behavior.
cc @UniqMartin

test: Replace "pass" with "skip".

---

lib/macho/fat_file.rb

Nothing major here, just getting rid of the `synchronize_` terminology we decided against earlier with `MachOFile` and making `FatFile` more similar to its single-arch counterpart.

FatFile refactoring

---

lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/sections.rb
lib/macho/utils.rb
test/test_create_load_commands.rb
test/test_fat.rb
test/test_macho.rb
test/test_serialize_load_commands.rb

Corresponds to #47.
Major changes:
Everything in *headers.rb* is now namespaced under `MachO::Headers`
Everything in *load_commands.rb* is now namespaced under `MachO::LoadCommands`.
Everything in *sections.rb* is now namespaced under `MachO::Sections`.

[WIP] Constant Isolation

---

lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/tools.rb
test/test_fat.rb
test/test_tools.rb

This adds `MachO::FatFile.new_from_machos(*machos)` and two serialization helper methods to support it, as well as `MachO::Tools.merge_machos(filename, *files)` as a convenience method.
It may also be nice to add a `MachO::FatFile#insert_macho` method, which would be used to merge a single-arch Mach-O into an extant `MachO::FatFile`.

Support for creating universal binaries from separate single-arch Mach-Os

---

lib/macho.rb
lib/macho/exceptions.rb
lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/sections.rb
lib/macho/structure.rb
lib/macho/tools.rb
lib/macho/utils.rb

Just doing some code reduction/housework.
```
fat_file: Add delegation to header/canonical Mach-O where possible.
The "canonical" Mach-O for a fat file is just the first Mach-O,
used to obtain attributes that should be constant across all
slices.
macho_file: Add delegation to header, fix YARD errors.
load_commands: Fix typo.
```

General cleanup.

---

.rubocop.yml
Gemfile
Gemfile.lock
README.md
test/helpers.rb

This replaces Coveralls.
cc @MikeMcQuaid

test: Use Codecov for coverage reports

---

lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/sections.rb
lib/macho/structure.rb
lib/macho/view.rb
test/test_fat.rb
test/test_macho.rb

This commit adds support for `#to_h` to core ruby-macho classes.
TODO:

lib: #to_h support

---

lib/macho/exceptions.rb
lib/macho/fat_file.rb
lib/macho/headers.rb
lib/macho/tools.rb
lib/macho/utils.rb

macho: `FatArch64` support

---

lib/macho/headers.rb

Based on binary samples, it looks like `CPU_TYPE_ARM64_32` is the same
constant as `CPU_TYPE_ARM`, ORed with a new ABI flag
(`0x02000000`, instead of `0x01000000` for `CPU_ARCH_ABI64`). Similarly,
the only CPU subtype seen so far appears to be a direct copy of
`CPU_SUBTYPE_ARM64_V8` and `CPU_SUBTYPE_ARM_V8` (`0x1`).
Fixes #113.

headers: Add ARM64_32 constants

---

lib/macho/load_commands.rb

See https://github.com/Homebrew/ruby-macho/pull/260#issuecomment-703460632.

macho/load_commands: Add new load commands

---

lib/macho.rb
lib/macho/tools.rb

If we make any changes to a signed binary, we invalidate the signature. Without resigning, the resulting binary is unusable. To my knowledge, there's no disadvantage to signing an unsigned binary using an ad-hoc signature, so we can just do this unconditionally to ensure we don't end up creating bad binaries. The ad-hoc signature should always be available and always work, so this should be safe to do in all circumstances.
I do still need to confirm which OS versions this will work with.

Apply an ad-hoc signature after modifying IDs

---

lib/macho.rb
lib/macho/exceptions.rb

This turned out to cause problems with certain exotic dylibs. Leaving this a warning should be safer instead.
refs https://github.com/Homebrew/brew/issues/8922

MachO: downgrade codesigning failures to a warning

---

lib/macho.rb

Replaces `system` with `Open3.capture3` to collect `codesign`'s output and error streams.

fix(macho): Silence the call to `codesign`

---

lib/macho.rb
lib/macho/tools.rb

As explained in https://github.com/Homebrew/brew/pull/9040#issuecomment-723888003 I think it's more desirable to have the `codesign!` calls happen inside Homebrew/brew instead of inside `macho/tools` methods.
This makes it easier for Homebrew to turn this functionality on/off, change what platforms are affected, etc. without needing to tag and vendor a new release each time.

macho: require `codesign!` call to be done explicitly.

---

lib/macho/macho_file.rb
test/test_macho.rb

Since `delete_rpath` differs from the behaviour of `otool` in that
duplicate rpaths are deleted in a single invocation, we should be
consistent with that and not report duplicates even when they exist.
Otherwise, this can break workflows that iterate through a macho-o
file's rpaths and does something with each of them. I currently have a
workaround for this in brew [1], but I realised this should actually
probably be fixed here.
[1] https://github.com/Homebrew/brew/pull/11392

Delete rpaths one at a time

---

lib/macho/headers.rb
lib/macho/load_commands.rb
lib/macho/macho_file.rb
test/test_kc.rb

The macOS 11/12 system uses a new scheme of KextCollections (BootKernelCollection, AuxiliaryKernelCollection, etc).  These are created as MH_FILESET objects.  This PR completes support for MH_FILESET and its related load commands

Support for MH_FILESET

---

lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/sections.rb
test/test_macho.rb

These two predicates replace the `Section#flag?` predicate, which
has unintuitive behavior and is now deprecated.
Closes #423.

sections: add `Section#type?` and `Section#attribute?`

---

lib/macho/load_commands.rb
lib/macho/macho_file.rb
lib/macho/view.rb
test/test_create_load_commands.rb
test/test_fat.rb
test/test_kc.rb
test/test_macho.rb

Using 'macho' in Pry/IRB was slow due to the editor printing the entire contents of @raw_data, this makes the inspect element print only the length of the view.

Fix for using `macho` in Pry/IRB

---

.github/workflows/tests.yml
Gemfile
Gemfile.lock
test/helpers.rb

Use a general Cobertura gem and then feed that into Codecov's GitHub Action.
This allow will allow Simplecov 0.22 to be used (not updated in this PR).
Fixes #601.

Migrate from deprecated Codecov Ruby gem

---

.github/workflows/tests.yml

`3.0` is interpreted as a number (`3`) so was actually testing the latest Ruby 3.x.

workflows/tests: fix Ruby 3.0 test

---

lib/macho/load_commands.rb

macho/load_commands: support LC_ATOM_INFO

---

lib/macho.rb

Bumps the version; will tag and release once this is on `master`.

macho: 4.1.0

---

.github/workflows/release.yml
Rakefile

This moves ruby-macho from a "William pushes it from his desktop" release process to a CI-managed one, with Trusted Publishing as the authentication mechanism.
Anybody with the ability to create releases on this repo can now release from it. The workflow itself is currently tied to the `rubygems.org` deployment environment, to which we could add signoff restrictions as well.
NB: I've already configured the Trusted Publisher for ruby-macho on RubyGems:
Closes #273

workflows: add a release workflow

---

ruby-macho.gemspec

I noticed that the project already has a funding link (https://github.com/sponsors/Homebrew). This PR adds the `funding_uri` to the gemspec to help increase visibility using the `bundle fund` command in Bundler.

Add funding_uri to gemspec

---

.github/workflows/release.yml
.github/workflows/tests.yml

This helps with transparency and they get updated by Dependabot.

workflows: use full version numbers

---

.github/workflows/release.yml

For a release workflow, it's best to use a clean environment.

workflows/release: use clean environment
